interval: "20min"
logging: "debug"
debug: "true"

email:
    host: "locahost"
    port: 23
    user: ""
    pass: ""
    sendby: "notify-gateway@youmi.net"

pushover:
    token: "token1"

mailto:
    -
        name: gateway
        email: [abc.youmi.net, bcd.youomi.net]

alerts:
    -
        name: "memory"
        query: "aliasByNode(collectd.*.memory.memory-free, 1)"
        interval: "2min"
        format: "bytes"
        mailto: ["gateway"]
        pushover: ["gateway", "sysadm"]
        rules: ["warning: > 300MB", "critical: > 600MB"]
